services:
  - type: web
    name: interview-genie-server
    env: node
    plan: free
    rootDir: web-server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://iGenie_user_db:Subhradip%401@cluster0.yh3chfn.mongodb.net/interview-genie?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "igenie_secret_key_2025_secure"
      - key: RAZORPAY_KEY_ID
        value: "rzp_test_RoI79b29xp6b0N"
      - key: RAZORPAY_KEY_SECRET
        value: "AT5ZHmI9RU6ohktqPXb4OhIN"
      - key: GOOGLE_CLIENT_ID
        value: "1006736129206-nuusm1qrqbhnuaf2nvk4h0q26g1270nq.apps.googleusercontent.com"
      - key: GOOGLE_CLIENT_SECRET
        value: "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"
